OBJDIR = build
SHLIB_EXT = dll
SHLIB_FLAGS = -shared -fpic
LA_LIBS = -L$(HOME)/code/OpenBLAS -lopenblas_haswell-r0.2.16.dev -lgfortran -lquadmath
LUA_INC = 
LUA_LIB = -Wl,-Bdynamic -llua -Wl,-Bstatic
LUA_MODULE_LIB = -DLUA_BUILD_AS_DLL -Wl,-Bdynamic -llua.dll -Wl,-Bstatic

CFLAGS += -O2 -Wall -march=native -fcx-limited-range -fno-exceptions -static
#CFLAGS += -g -O0 -Wall -march=native -fcx-limited-range -fno-exceptions -DENABLE_S4_TRACE
CXXFLAGS = $(CFLAGS)

CC = gcc
CXX = g++
