OBJDIR = build
SHLIB_EXT = so
SHLIB_FLAGS = -bundle -undefined dynamic_lookup
LA_LIBS = -framework Accelerate
LUA_INC = -I/usr/local/include/lua5.2
LUA_LIB = -L/usr/local/lib -llua
LUA_MODULE_LIB =

OPTFLAGS = -O2
CFLAGS += $(OPTFLAGS) -Wall
CXXFLAGS += $(OPTFLAGS) -Wall -std=c++11 -DHAVE_LAPACK -DHAVE_BLAS

CC = cc
CXX = c++
